### ISSUE TITLE
Resizing Already Uploaded Images

### ISSUE THREAD

**Issue by purplespider** [heyday/silverstripe-optimisedimage#11]
I often end up adding this module to a site after the owners have gone and batch uploaded many high res images via SilverStripe and maxed out their disk space. This deals with any future uploads, but for the images that have already been uploaded, I end up downloading them, resizing them locally and then reuploading them, overwriting the high res versions.

Is there any way to batch run a resize on images that had been uploaded before the module was installed?

**Comment by stecman** [comment]
There's no task built in to do this, but since the [resampling extension uses onAfterWrite](https://github.com/heyday/silverstripe-optimisedimage/blob/master/code/ResampleImage.php#L76-L79), you may be able to just loop over all images and write them again:

```php
foreach (Image::get() as $image) {
    $image->write();
}
```
