### ISSUE TITLE
PHP Notice:  getimagesize(): Read error!

### ISSUE THREAD

**Issue by hpeide** [heyday/silverstripe-optimisedimage#12]
The getimagesize throws exeption when used with CloudAssets module. 

When uploading completes a error message as this shows in the upload field:
Object->__call(): the method 'parent' does not exist on 'Image'

The image get saved on the server and if you have configured the upload field to overwrite existing a second upload will go through and work fine.

Wrapping a try-catch around getImagesize in ImageOptimiserService::optimiseImage [43] fixes the issue.
E.g like this:
`try {
                list($width, $height, $type, $attr) = getimagesize($filename);
            } catch (Exception $e) {
                $this->logger->error(
                    "Unable to get image size.",
                    array(
                        'exception' => $e
                    )
                );
            }
`

I can create a pull request if this looks ok?

**Comment by camspiers** [comment]
I've reviewed the PR. Again, thanks for reporting this, it is a good catch!

**Comment by camspiers** [comment]
Made a new release. Version 2.2.2. Again thanks for the report and the fix!
