### ISSUE TITLE
Global jpegopti

### ISSUE THREAD

**Issue by NobrainerWeb** [heyday/silverstripe-optimisedimage#8]
I have jpegopti and pngopti installed so i can just type jpegopti in the terminal, no need for a path.
I can't seem to allow for that, if i define binDirectory: '' (empty string) it's looks for /jpegopti.
Would it be possible to have only the command called? No need for different settings across servers then

**Comment by camspiers** [comment]
The command "templates" that are used can be changed, so it is just a matter of changing the template for the command you are having trouble with, and making it so it doesn't use the binDirectory:

```json
---
After: 'silverstripe-optimisedimage/config#core'
---
ImageOptimiserService:
  availableCommands:
    jpg:
      jpegoptim: 'jpegoptim -p -m%3$d --strip-all %2$s'
```

Hope that makes sense!

**Comment by NobrainerWeb** [comment]
Super, thanks :-)
