### ISSUE TITLE
Command works from commandline, but script does nothing

### ISSUE THREAD

**Issue by NobrainerWeb** [heyday/silverstripe-optimisedimage#9]
I'm having some issues, and i don't really know how to debug this stuff.
When i do a flush=1 images are created.
Added an echo sprintf($command ... which gives me a string like 
jpegoptim -p -m80 --strip-all '/Applications/MAMP/htdocs/flammen-cms/assets/HeroImages/_resampled/CroppedFocusedImage62080050-61-header4.jpg
The file is not optimized though. If i take the string and run it in commandline, it optimizes the image.

Is this a problem with me using CroppedFocusedImage? or how can i debug?

**Comment by stecman** [comment]
Hey @NobrainerWeb, the best place to debug this is probably in `[ImageOptimiserService::execCommand](https://github.com/heyday/silverstripe-optimisedimage/blob/master/code/ImageOptimiserService.php#L138)`.

Also, check the full program path in the generated command against the output of `which jpegoptim` on the command line; I suspect they might be different. If they are different see #8, or set the binary path in your config:

```yaml
ImageOptimiserService:
  binDirectory: [path where jpegoptim binary is - something like /usr/bin]
```

This module really needs to be changed to not use an absolute path by default.

**Comment by camspiers** [comment]
You can attach a logger to the optimiser service that will provide errors to the logger.
